---

# Install Linux packages
- name: install Linux packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - python-pip
    - python-wheel
    - expect
    - libaio
    - yum-utils
    - sg3_utils

# Upgrade pip
- name: upgrade pip
  pip:
    name: pip
    extra_args: --upgrade pip

# Upgrade packages
- name: upgrade all packages
  yum:
    name: "*"
    state: latest

# Update /etc/hosts
- name: set /etc/hosts remove 127.0.0.1 for hostname
  lineinfile: 
    path: /etc/hosts 
    regexp: '^127\.0\.0\.1.*{{ ansible_hostname }}'
    state: absent

- name: Update hostfile
  lineinfile:
    path: /etc/hosts
    state: present
    line: "{{ item }}"
  with_items:
    - '{{ ansible_eth1.ipv4.address }} {{ ansible_fqdn }} {{ ansible_hostname }}'

# Update /etc/sysctl.conf
- name: update /etc/sysctl.conf
  lineinfile:
   path: /etc/sysctl.d/99-sysctl.conf
   line: "{{ item }}"
  with_items:
    - 'net.ipv4.conf.default.rp_filter = 2'
    - 'net.ipv4.conf.all.rp_filter = 2'

# re-read settings
- name: re-read settings
  shell: sysctl --system

# Disable Firewalld
- name: Disable firewalld
  shell: systemctl disable firewalld

# Disable SELinux
- name: Disable SELinux
  selinux:
    state: disabled

# Create oracle group(s)
- name: Create oinstall group
  group:
    name: oinstall
    gid: 54321
    state: present

# Create Oracle user
- name: Create oracle user
  user:
    name: oracle
    uid: 54321
    group: oinstall
    comment: oracle user

- name: Create ORACLE_HOME mount point
  file:
    path: /opt/oracle/product
    state: directory
    owner: oracle
    group: oinstall
    mode: 0755

- name: Create oradata mount point
  file:
    path: /opt/oracle/oradata
    state: directory
    owner: oracle
    group: oinstall
    mode: 0755

# Create Tomcat user
- name: Add Tomcat user
  user:
    name: tomcat
    comment: tomcat webserver user

# Create Tomcat Directories
- name: Create /u01 directory
  file:
    path: /u01
    state: directory
    owner: tomcat
    group: tomcat
    mode: 0777
